---
# tasks file for ansible-role-server-proxy-repo
- name: Install CentOS-Base.repo
  include_tasks: centos/centos-8-base.yaml
  when: 
    - ansible_facts['distribution'] == "CentOS"
    - ansible_facts['distribution_major_version'] == "8"