---
# tasks file for ansible-role-server-proxy-repo

- name: Load a variable file based on the OS type
  include_vars: "{{ lookup('first_found', params) }}"
  vars:
    params:
      files:
        - '{{ansible_distribution}}.yaml'
      paths:
        - 'vars'
        
- name: Setup Repo list for CentOS 8
  when: 
    - ansible_facts['distribution'] == "CentOS"
    - ansible_facts['distribution_major_version'] == "8"
  block:
    - name: Install CentOS-Base.repo
      include_tasks: centos/centos-8-base.yaml